import type { Metadata } from "next";
import { Geist, Lato } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";
import ProviderSes from "./context/ProviderContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "TWITTER PARODY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased`}>
        <ProviderSes>
          <ThemeProvider>
          <div id="modal-root" />
            {children}</ThemeProvider>
        </ProviderSes>
      </body>
    </html>
  );
}
